Everything's connected end to end now. Fast API serving real trend data and comparison results react rendering both pages against it worth a quick gut check while it's fresh. Try switching a few different countries on trends and try a real before after image pair, not identical ones on compare, just to see how the overlay looks with actual change detected rather than the zero diff test case. Whenever you're ready, this is a good point to commit. You've got a real working milestone. Just say the word git commit or however you want to phrase it, and I'll walk you through it step by step since you're still getting comfortable with Git's good milestone to have live on GitHub first real end to end feature working real data in real prediction out both pages talking to a working back end where do you want to go next? Start on the jit in or cleanup making sure NV Node slash modules PiCash model pkl if it's large, et cetera aren't tracked, write a read me or move on to the next feature a clean, efficient repo, good instinct to do this before the Read Me, since the Read Me will reference the project structure and that's easier to write once it's tidy. First, let's find out what to actually track right now. Since Venves and Node modules were visible in your VS code explorer earlier, there's a chance they got committed before any daulk jit in your existed, which would make your repo unnecessarily huge. Open git bash in the project Root and Run Code Block paste back whatever it prints, even if it's empty, that tells us something toowhile you check that here's the jit in your I'd put at the project route users an admin flash projects Calius Plass Bunch Jignore. A couple of notes on the choices in there MLS model PKL is ignored. It's a generated artifact, regenerated by running train classifier Pi, not source code. Same reasoning as DOC jit ignoring Picache no point versioning something that's rebuilt from other files MLC is ignored. The URSAT dataset is a few hundred mb downloaded from Xenodo. Definitely not something to push to GitHub. This means anyone cloning your repo, including future U on a new machine, needs to re download the dataset and rerun training before compare will work worth a line in the red me about that drop this jit in or at the project route same level as back end slash front end line ml then run the check command above and paste the result that tells us whether we also need to untrack anything that's already sitting in Gistory"""
ML: forest vs. non-forest image classifier.

Dataset: EuroSAT RGB - real Sentinel-2 satellite image patches, labeled by
land cover type. Download and extract first:
https://zenodo.org/records/7711810/files/EuroSAT_RGB.zip?download=1

Expected layout after extracting:
ml/data/EuroSAT_RGB/Forest/...
ml/data/EuroSAT_RGB/AnnualCrop/...
ml/data/EuroSAT_RGB/Pasture/...
(10 folders total)

Each image gets shrunk down and flattened into a list of numbers - each
pixel's red/green/blue value becomes one feature. A random forest then
learns which pixel patterns tend to show up in forest vs everything else.
"""

import random
from pathlib import Path

import joblib
import numpy as np
from PIL import Image
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

DATA_DIR = Path("data/EuroSAT_RGB")
IMAGE_SIZE = 16  # shrink each image before flattening, keeps training fast
FOREST_COUNT = 600
NON_FOREST_COUNT = 600  # spread evenly across the other 9 classes
RANDOM_SEED = 42
MODEL_PATH = "model.pkl"  # the backend loads this same file for predictions

random.seed(RANDOM_SEED)


def load_images(folder, limit):
    paths = list(folder.glob("*.jpg"))
    random.shuffle(paths)
    paths = paths[:limit]
    images = []
    for path in paths:
        img = Image.open(path).convert("RGB").resize((IMAGE_SIZE, IMAGE_SIZE))
        images.append(np.array(img).flatten() / 255.0)
    return images


class_folders = sorted(p for p in DATA_DIR.iterdir() if p.is_dir())
print(f"found classes: {[p.name for p in class_folders]}")

non_forest_per_class = NON_FOREST_COUNT // (len(class_folders) - 1)

X = []
y = []
for folder in class_folders:
    if folder.name == "Forest":
        limit = FOREST_COUNT
        label = 1
    else:
        limit = non_forest_per_class
        label = 0

    images = load_images(folder, limit)
    X.extend(images)
    y.extend([label] * len(images))
    print(f"  {folder.name}: {len(images)} images loaded")

X = np.array(X)
y = np.array(y)
print(f"\ntotal: {len(X)} images ({int(y.sum())} forest, {len(y) - int(y.sum())} not forest)")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_SEED, stratify=y
)

model = RandomForestClassifier(n_estimators=200, random_state=RANDOM_SEED)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("\n" + classification_report(y_test, y_pred, target_names=["not forest", "forest"]))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(5, 5))
plt.imshow(cm, cmap="Blues")
plt.xticks([0, 1], ["not forest", "forest"])
plt.yticks([0, 1], ["not forest", "forest"])
plt.xlabel("predicted")
plt.ylabel("actual")
plt.title("Confusion matrix")
for i in range(2):
    for j in range(2):
        plt.text(j, i, cm[i, j], ha="center", va="center")
plt.tight_layout()
plt.savefig("output/confusion_matrix.png", dpi=150)
print("saved output/confusion_matrix.png")

joblib.dump(model, MODEL_PATH)
print(f"saved {MODEL_PATH}")
